stages:
  # Tahap 1: Persiapan Data
  prepare:
    cmd: python src/data_preparation.py
    deps:
      - src/data_preparation.py
      - data/raw/Data_running.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
      - reports/eda_distribusi_level.png

  # Tahap 2: Pelatihan Model
  train:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/model_rekomendasi.pkl